const admin = require("firebase-admin");
require("dotenv").config();
const serviceAccount = {
  type: process.env.FIREBASE_TYPE,
  project_id: process.env.FIREBASE_PROJECT_ID,
  private_key_id: process.env.FIREBASE_PRIVATE_KEY_ID,
  private_key: `-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDrGUJA+kRdhiTX\nGVNXk4oPnYLm+963JpYTaw5wvDJbSPuMvwwhQNy2EuBwRQ2Njh11Arl5OpieQPqC\n3DPGuNS0y25Bkfy9QrRvGeu3JJdUfPW1zKSCO9UgL5WA8jhs2ODNZMstTbwiBEE+\nkbjvOdZMMXCylNP2npy+yrC6ypTORJVwzNoH8bh2Db8R1flSS1qAJ5z2190gOqrR\nMaoQhKu1q7oQxB2MQN23+EAGvj+FlVToIdcGAAj7FPzttgUz8h7hb0Dsc5BUgiXB\nTOgp7wAIzQxAGIf5HjjKRpKKZ+bjePQgT407iqEj9Fn492e70nX+X5BBqVSOOu5W\nWhizrmG/AgMBAAECggEAVrpAMzk/3CJ+16z7jkyau0z3e9+Blx4QcgRl1NfQWdWQ\nGqllv6SuZyqKilAnAkfhfQduxZaEs6iz4W97WD1aFoIPX/gLfQQtDOlKiArjGqNo\nf1MJgxOweUmkhOeWQi01rP+YZlONah0YtozKZNH4yK3abb6yfQGhQE8EqDvQblCw\nqFdEW2L2DAnX/mEsz8b4wXObDDoR3/gNS1yJ3GerwktQgqIKyhFYKDANMWl8bHGD\n142GTCN4XQlqkj8/HPoXW77piNzEadxRRjCz4rIEvRWqzfESOXAZYejHZhCdvYBr\nJcTKvEPjhZ2lueYas2REZQLuoOwnUmxOR+gPk8evcQKBgQD6NV+p7IRpaJ8+y/Tn\nB/6nL6dkO20yYokS2V5TYb/ZM1cqwAMXkkDL6pWa6aXRkCt4j85YoEySPxEFs5hT\nXFeB9WcTUlu+DKe+JTspMJacxN3hIddkXvu7ex6CIhUzWV9gl3JOq457nqnu3lHa\ncqYMX8a7F0SjbCU0jittEumdzwKBgQDwilnUWoWyDA/B6nQoiwf9SeEI87Hi2GZB\nwUjQSlFhq4PAOGjo1cTwd+ppFLOwgTJkwn8BMuzH6yzOObiJP2i3C9kxU4awPzct\nUXi0kPj3r/pfX2tRWdNXFAmc3T6O5qZLZX+Qta9elWkMUsOIc7xI6GRj42HC9AnD\ndTcprb9pEQKBgQCzuVD8+sJmANuaPOCubuSxbJ59dd5K+dJiMrb5h9ZJiwJK19+g\nt9JJZziNLNWKAVfoYsuih4pY5mowwT9iaYsF86NVkqwJiIeZIp8rSBZ3h0WlaCyS\nkVOa6KYSba7y0nibJk3aSoqvK1n/FbyQABhb/RP/4YfRJ2ZWKOTylUovqwKBgQCO\nWkJZQw02Vp8Isvj1eXpL8uoDwzz2M/0oUvwFkMXi2H9LRdcIXGKFsWH/uCmzfnJV\nYSmKixnIIqzMiypjxyvwkEmEQJtIONEtt7aInfdJllLFGJJJfbBuK0SZGfJI3cVy\nf2nkOTHE9wVJLr3bRisatrWay9lyZ7xTeU4hE1thEQKBgQDE/THDqYr0Ku6SxKOt\nWFu1BUe+7rRJHZA9UjqUHstOJeyL0u0aFyic/Vwd4DkrALSJ0B8Tysy3QETL7bT2\nmKUA4J/JLEqayNH0mMiwBjY+Y9J+D3wleuPnVKUuKOnalKFyhK7lFphzx3ebUK8Z\ni7XMTp7qJBv8M3uE2+nKUtoMBA==\n-----END PRIVATE KEY-----\n`,
  client_email: process.env.FIREBASE_CLIENT_EMAIL,
  client_id: process.env.FIREBASE_CLIENT_ID,
  auth_uri: process.env.FIREBASE_AUTH_URI,
  token_uri: process.env.FIREBASE_TOKEN_URI,
  auth_provider_x509_cert_url: process.env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
  client_x509_cert_url: process.env.FIREBASE_CLIENT_X509_CERT_URL,
  universe_domain: process.env.FIREBASE_UNIVERSE_DOMAIN,
}; // Adjust the path to your key file

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

module.exports = admin;
